apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlopsnginx3
spec:
  replicas: 1
  selector:
    matchLabels:
      run: mlopsnginx3
  template:
    metadata:
      labels:
        run: mlopsnginx3
    spec:
      containers:
      - image: nginx
        name: mlopsnginx3
        ports:
        - containerPort: 80