apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlopsnginx2
spec:
  replicas: 1
  selector:
    matchLabels:
      run: mlopsnginx2
  template:
    metadata:
      labels:
        run: mlopsnginx2
    spec:
      containers:
      - image: nginx
        name: mlopsnginx2
        ports:
        - containerPort: 80